dist: trusty
addons:
  chrome: stable
language: ruby
rvm:
- 2.5.1
cache: bundler
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails assets:precompile
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: MNoHyerIMnC4nWTDsDm3XK+Q0O2uIQMykjdB7r05DsJPu0UHIhrzjKGgOR4rj66MrXmwjWbvu77kZHcUIaScJndqY+GdI+Hwe5A3BxetkzMw5N400MQsRq7kFTKrwmHry/Gc0U7BwVw3+nVYOD3z+/m/lwTaVch8kCbfCcLOVPdZxjwKNxomIf+S7n9sccaAUcgHuRYg8XT17JZBRG+VuzY3M1+VW2jj3CD1C+sVGosd3Dg3WKGHnUL7AUT4OALHdQ+46P/++6UTv8+y6h7QDldzBQd2q004KYdXRc4ZKxxHJn6C9y8FfkKCyxZvp7OsYlMCueBM2sUayj86YEs/1XpV596eTDKbSrRAHhH3WTytk15uUgJmLebjFyheQDQ+eHqDBCMHs1jR9iwz741WVG2Rp/bKnmRUqBsfaZWUB/p5NamhTJO0PKHZ3cpa8yoj0zGiJUVbiED1FZ9IXYzq5u29y/dBDE7sWXS4lxWLYJEGlScSQ00e1q9iFvSVY/j73SZd/oC3VUjXVd9oWPusqDcx/pSZn7JQwj81Kj2QUTxKuu4IGcvQc2dkjqETaCjAbVw9sBvpicRRY2Z6FUkgH62BmKaO1Qvop/4WQ7bKQJHiqI5HL+mwz8vUL1aISQn5S4OQH6MGZdXnfWm/VRFLTxvr1T2U4gsh/X6RpdJ8OCU=
