dist: trusty
addons:
  chrome: stable
language: ruby
rvm:
- 2.5.1
cache: bundler
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails assets:precompile
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: qAtbxeZB5YFU9h/GFWfMbz70qPqslgfjgURmhH9MDgOzgoHFbYFjlv/37d8xPHeXf3kGc+URyWHjVHSwqlmZDc235Yi2Co5u8HpQ6cRAnQooAJQjLjY4EbRPSsX/7Xxe3sgYhhHTpxurqyQ1k3a7fseBhOxheQFKLtlgZi928+Nis2ln1stQF4dbr/SHptuudv6XSxQtt9GyOXu/T7zXHdkEjTwrbVVOJ3FBVSfHdD3GpC7NoOF8V2K0aWJdxXMMxsAxn09Nin1Pi4vzVG/7SR9FTXJZGHtYU5xq1P5n0FuHumHf0E+CByLi6ygtoObMt8ASFtvDfpD3UFJOYGFhtJ8JF9VNOykZTUv4Pj3VeBdyrGtquLuRa04mM5E2uG4HY/SYNFkeW0j4nR/qtwV7yAaiQ8QxzbV59/x4rvmZzGeWJD4R6WNc9eHB0zMZON9DeeKCQdVcznciyiOs8CwcXqYqeUu4Z7wD8PGqwd1d+xQJKXYKo3G/QigfSiu+iu/N1VwfuST774jmCjPwbBvYCJ1rtWSaxvmuABNVrYROAD+5cVn4W8ZwMbN1bwlYB9F3+nWV820okOkjXYslre2XHJsAtU1dX4MjZlBB1GX4gh4GvnQwA6MwQdMtss6QmpUalZ6/Ie2vO89oSce7Upcao1/JCe0t5LdwRs4KqeXchMs=
  app: justanothertodolist
  on:
    repo: thomasjlee/justanothertodolist
  api_Key:
    secure: BGUHY32l/Fg2wR0ni49nH90cU9oGCKaQZPkLjSnFPcR2mAq8eYCMnskMw0ku9vPVu4WEVMHEIy64KJuHYwMaACPXw3041SI41mfY5DIem2DSssFuxHoAghWT0rycbKok6vKAr17yklzSZMBNMa4ESWZPt5MNL76q90gyeqJC58g9p6AMVSwljI4G4GGt1+OrivsWNwlgl7a1sRarMsGFkiJDYyaRAa129B1bQV3GuFZ93D6vmrhkRT/GjD0qiTvpHa/K/kl5kInRARrOJ5RsIx27KLj9mK+/FjbbFcozuQq0ur++y8Ir9ilNax5Odt49DMkplcrRug29j5cxJI/DdDVeOJjJf6TJ8j6b/Mcgq5AlrQxAjv0G1jjuM5UxSp+nc0EJm5ftaxUPmVt9oVaqfvJZtGhRjQCRc1eriILt2Q+v+DuHOugpzoXpjIE7oXWfpNwB8K70FxIQnwypVe6eLi4crDhEKM30NzT2aH4Kiaqfr0qmjyTUD4KfSSjWNjfB0sdi3jk0Wrhu3iBYltKG2hZzlC8lwZZbj9nwdOSOfJluVVr/nL9DpAZwaT6gwHxQkYxe0qLyVuJL+LRn3t66YzDSubFm5WJbZ3+lQUyl55N1SRi53hA6CnbVP7MTev0JCaA716PoQtFJM2QXrimzmvN06piv7rUgK5FBj54PTrQ=
