dist: trusty
addons:
  chrome: stable
language: ruby
rvm:
- 2.5.1
cache: bundler
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails assets:precompile
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: POFcVwbdAH+o0RkS5gfU36SIaVlSXBM/D4GVjzvnM6x4NgZyVkmDTPVPfbUHEuIs54qhc78cmCWGOMpmimzFm7qf9LyU2KL25Z7uquOeWb92AliAtPI8aRu1KVD5cw7K+oNHTzj6gxXkXoc5Mif8u9MjzTIyNPXSkKTOffyp4IcD9GkOERt/ychNlV+ktz6qE2bcGmg/nQ24XIV2aV/y9MezgxzaHpdP+6tAqc2FAHtiGjoj/Z/pjjquZD49AHXg3aiQrmi02WA/+1KM5SLK5HyX1ikkQOsBcWvAc8nxHtaRfiIHRpe7nvsDUp2bsKS+h7o2v4haK9TvKo+cEt2FrIGvn9TdYbw6DM8nfJohYl/RH1+WK1ftmvkYgQnetWZ3BdajMDN/W3Uvl8TlbYQ03/t2x4TJZWDzkkuhqg9pcoAZr8O08YEuS7hj5gZiDZykbORRVvXiUCNv0590BNDqL33GUT23+qt9VocXJ6YEqnxqIAT33pjdSrkI1tlQv/BRqacZO0+44R11ADlkzyZ3Kf17RhaoFLvjiF6XSdzCfmWkTGGYGArXBAWg4fufnAecQ0GzYPH1fnXyjg1tL+tVlt2VKDwWNIvCvlFgwvdknSHdeiL4SMfsfFqlCtVAP/vVlQIRIocuueiUVPDxZrg/JdZjgw4K1IhcnQecv/67pRU=
  app: justanothertodolist
  on:
    repo: thomasjlee/justanothertodolist
  api_Key:
    secure: BGUHY32l/Fg2wR0ni49nH90cU9oGCKaQZPkLjSnFPcR2mAq8eYCMnskMw0ku9vPVu4WEVMHEIy64KJuHYwMaACPXw3041SI41mfY5DIem2DSssFuxHoAghWT0rycbKok6vKAr17yklzSZMBNMa4ESWZPt5MNL76q90gyeqJC58g9p6AMVSwljI4G4GGt1+OrivsWNwlgl7a1sRarMsGFkiJDYyaRAa129B1bQV3GuFZ93D6vmrhkRT/GjD0qiTvpHa/K/kl5kInRARrOJ5RsIx27KLj9mK+/FjbbFcozuQq0ur++y8Ir9ilNax5Odt49DMkplcrRug29j5cxJI/DdDVeOJjJf6TJ8j6b/Mcgq5AlrQxAjv0G1jjuM5UxSp+nc0EJm5ftaxUPmVt9oVaqfvJZtGhRjQCRc1eriILt2Q+v+DuHOugpzoXpjIE7oXWfpNwB8K70FxIQnwypVe6eLi4crDhEKM30NzT2aH4Kiaqfr0qmjyTUD4KfSSjWNjfB0sdi3jk0Wrhu3iBYltKG2hZzlC8lwZZbj9nwdOSOfJluVVr/nL9DpAZwaT6gwHxQkYxe0qLyVuJL+LRn3t66YzDSubFm5WJbZ3+lQUyl55N1SRi53hA6CnbVP7MTev0JCaA716PoQtFJM2QXrimzmvN06piv7rUgK5FBj54PTrQ=
